mqtt:
  server: test.mosquitto.org
  port: 8883
  id: laboratorio
  tls: false
  username:
  password:

storage:
  filename: ./data.log
  filter: 30

anayzers:
  - name: DioxidoNitroso
    class: EcoPhysicsNOx
    port: /dev/ttyUSB0
    address: 10
    topic: lea/nox
  - name: DioxidoAzufre
    class: AF22M
    port: /dev/ttyS1
    topic: lea/azufre
  - name: Ozono
    class: O341M
    port: /dev/ttyS2
    topic: lea/ozono
